export const GAME = {
  MAX_ENEMIES: 15,
  MAX_PROJECTILES: 20,
  FIRE_INTERVAL_MS: 600,
  FIRE_INTERVAL_BUFFED_MS: 250,
  SPAWN_INTERVAL_START_MS: 2000,
  SPAWN_INTERVAL_MIN_MS: 400,
  FEVER_COMBO_THRESHOLD: 10,
  FEVER_DURATION_MS: 8000,
  FEVER_SCORE_MULTIPLIER: 3,
  BUFF_DURATION_MS: 10000,
  RESUME_COUNTDOWN_MS: 1500,
  ITEM_DROP_CHANCE: 0.12,
  PROJECTILE_SIZE_BUFF_MULTIPLIER: 1.5,
  DAMAGE_BUFF_AMOUNT: 1,
} as const

export const SCORE = {
  NORMAL: 10,
  HEAVY: 25,
  ZIGZAG: 20,
  BOSS: 50,
} as const

export const ENEMY_HP = {
  NORMAL: 1,
  HEAVY: 2,
  ZIGZAG: 1,
  BOSS: 3,
} as const
